language: node_js
node_js:
  - "10"
before_install:
  - CHANGED=$(.travis/check-change "^$TRAVIS_JOB_NAME/|^\.travis.yml$|\.editorconfig$") && if [[ "$CHANGED" = "unchanged" ]]; then exit 0; fi
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "1.17.2"
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - cd $TRAVIS_JOB_NAME
  - yarn install
jobs:
    include:
        - stage: test
          name: fee-monitor
          os: linux
          script:
              - yarn lint
              - yarn build
        - name: helicopter
          os: linux
          before_script:
              - docker pull kodebox/codechain:v1.1.1
              - docker run -d -p 8080:8080 kodebox/codechain:v1.1.1 --jsonrpc-interface 0.0.0.0 -c solo --reseal-min-period 0 --enable-devel-api
              - psql -c 'CREATE DATABASE "codechain-indexer-dev";' -U postgres
              - psql -c "CREATE USER \"user\" WITH ENCRYPTED PASSWORD 'password';" -U postgres
              - docker ps -a
          script:
              - yarn lint
              - yarn build
              - git clone --depth 1 https://github.com/CodeChain-io/codechain-indexer.git
              - pushd codechain-indexer
              - yarn install
              - NODE_ENV=dev yarn run migrate
              - yarn start &
              - popd
              - NODE_ENV=test yarn test
        - name: indexer-watcher
          os: linux
          script:
              - yarn lint
              - yarn build
              - yarn test
        - name: juggle-ccc
          os: linux
          script:
              - yarn lint
              - yarn build
        - name: monitor
          os: linux
          script:
              - yarn lint
              - yarn test
              - yarn build
        - name: tick-tock
          os: linux
          before_script:
              - docker pull kodebox/codechain:v1.1.1
              - docker run -d -p 8080:8080 kodebox/codechain:v1.1.1 --jsonrpc-interface 0.0.0.0 -c solo --reseal-min-period 0 --enable-devel-api
              - psql -c 'CREATE DATABASE "codechain-indexer-dev";' -U postgres
              - psql -c "CREATE USER \"user\" WITH ENCRYPTED PASSWORD 'password';" -U postgres
              - docker ps -a
          script:
              - yarn lint
              - yarn build
              - git clone --depth 1 https://github.com/CodeChain-io/codechain-indexer.git
              - pushd codechain-indexer
              - yarn install
              - NODE_ENV=dev yarn run migrate
              - yarn start &
              - popd
              - NODE_ENV=test yarn test
        - name: timelock
          os: linux
          script:
              - yarn lint
              - yarn build
services:
  - docker
  - postgresql
addons:
  postgresql: "9.4"
cache: yarn
